[package]
name = "rongor_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
rongor = { path = "/Users/jjput/programmiren/Rust/rongor_engine_backup/rongor" }
macroquad = "0.4.5"
ndarray = "0.15.6"
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
